Repository Aloquei/aloquei_app, pull requests merged in 2021-09, with the labels that each got.

#81 Botao de favorito em moradias + nova tela interesse
  lib/blocs/home/home_bloc.dart
  lib/screens/app.dart
  lib/screens/core/navigation.dart
  lib/screens/detail_offers/detail_offer.dart
  lib/screens/explore/components/explore_app_bar.dart
  lib/screens/explore/components/house_list_view.dart
  lib/screens/explore_list/components/place_item.dart
  lib/screens/explore_person/components/explore_app_bar.dart
  lib/screens/explore_person/components/place_item.dart
  lib/screens/explore_person/explore_person.dart
  lib/screens/home/components/bottom_bar.dart
  lib/screens/home/home.dart
  lib/screens/hosting/components/host_appbar.dart
  lib/screens/hosting/components/host_select_menu_amenities.dart
  lib/screens/hosting/components/host_select_menu_desc_apt.dart
  lib/screens/hosting/components/host_select_menu_desc_bnb.dart
  lib/screens/hosting/components/host_select_menu_desc_hotel.dart
  lib/screens/hosting/components/host_select_menu_desc_house.dart
  lib/screens/hosting/components/host_select_menu_desc_unique.dart
  lib/screens/hosting/components/host_select_menu_desc_unit.dart
  lib/screens/hosting/components/host_select_menu_guest_num.dart
  lib/screens/hosting/components/host_select_menu_type.dart
  lib/screens/hosting/components/host_select_menu_type_size.dart
  lib/screens/hosting/host_page_address.dart
  lib/screens/hosting/host_page_amenities.dart
  lib/screens/hosting/host_page_desc.dart
  lib/screens/hosting/host_page_description.dart
  lib/screens/hosting/host_page_guest_number.dart
  lib/screens/hosting/host_page_photos.dart
  lib/screens/hosting/host_page_price.dart
  lib/screens/hosting/host_page_review.dart
  lib/screens/hosting/host_page_title.dart
  lib/screens/hosting/host_page_type.dart
  lib/screens/hosting/host_page_type_size.dart
  lib/screens/interest/components/interest_page_data.dart
  lib/screens/interest/components/interest_select_menu_desc_house.dart
  lib/screens/interest/components/interest_select_menu_gender.dart
  lib/screens/interest/components/interest_select_menu_pet.dart
  lib/screens/interest/interest_page_desc.dart
  lib/screens/interest/interest_page_gender.dart
  lib/screens/interest/interest_page_pet.dart
  lib/screens/person_list/person_list.dart
  lib/screens/profile/profile.dart
Labels: enhancement

#88 Feature/explore list bloc
  lib/blocs/explore_list/explore_list_bloc.dart
  lib/blocs/explore_list/explore_list_event.dart
  lib/blocs/explore_list/explore_list_state.dart
  lib/blocs/explore_people/explore_people_bloc.dart
  lib/blocs/explore_people/explore_people_event.dart
  lib/blocs/explore_people/explore_people_state.dart
  lib/blocs/home/home_bloc.dart
  lib/blocs/home/home_state.dart
  lib/blocs/search/search_bloc.dart
  lib/blocs/wishlist/wishlist_bloc.dart
  lib/core/definitions.dart
  lib/core/models/interest_offer_model.dart
  lib/core/models/offers_model.dart
  lib/core/models/user_model.dart
  lib/main.dart
  lib/resources/apis/ibge.dart
  lib/resources/favorites/firestore_favorites.dart
  lib/resources/offers/firestore_offers.dart
  lib/resources/user/firebase_user.dart
  lib/screens/app.dart
  lib/screens/explore_list/components/explore_app_bar.dart
  lib/screens/explore_list/components/list_places.dart
  lib/screens/explore_list/components/place_item.dart
  lib/screens/explore_list/explore_list.dart
  lib/screens/explore_people/components/explore_app_bar.dart
  lib/screens/explore_people/components/place_item.dart
  lib/screens/explore_people/explore_people.dart
  lib/screens/explore_person/explore_person.dart
  lib/screens/home/home.dart
  lib/screens/hosting/components/host_select_menu_amenities.dart
  lib/screens/hosting/components/host_select_menu_desc_apt.dart
  lib/screens/hosting/components/host_select_menu_desc_bnb.dart
  lib/screens/hosting/components/host_select_menu_desc_house.dart
  lib/screens/hosting/components/host_select_menu_desc_unique.dart
  lib/screens/hosting/components/host_select_menu_desc_unit.dart
  lib/screens/hosting/components/host_select_menu_type.dart
  lib/screens/hosting/components/host_select_menu_type_size.dart
  lib/screens/hosting/host_page_desc.dart
  lib/screens/hosting/host_page_description.dart
  lib/screens/hosting/host_page_price.dart
  lib/screens/hosting/host_page_title.dart
  lib/screens/hosting/host_page_type.dart
  lib/screens/interest/components/interest_page_data.dart
  lib/screens/interest/components/interest_page_description.dart
  lib/screens/interest/components/interest_select_menu_desc_house.dart
  lib/screens/interest/components/interest_select_menu_pet.dart
  lib/screens/interest/interest_page_desc.dart
  lib/screens/interest/interest_page_gender.dart
  lib/screens/person_list/person_list.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#83 Search filter
  lib/screens/filter/components/app_bar_content.dart
  lib/screens/filter/components/filter_appbar.dart
  lib/screens/filter/components/filter_checkbox.dart
  lib/screens/filter/components/filter_checkbox_text.dart
  lib/screens/filter/components/filter_counter.dart
  lib/screens/filter/components/filter_counter_container.dart
  lib/screens/filter/components/filter_slider.dart
  lib/screens/filter/components/filter_subtittle.dart
  lib/screens/filter/components/filter_title.dart
  lib/screens/filter/filter_page.dart
Labels: enhancement

#95 Feature/personal info bloc
  lib/blocs/auth/auth_bloc.dart
  lib/blocs/explore_list/explore_list_bloc.dart
  lib/blocs/explore_people/explore_people_bloc.dart
  lib/blocs/home/home_bloc.dart
  lib/blocs/profile/profile_bloc.dart
  lib/blocs/profile/profile_event.dart
  lib/blocs/profile/profile_state.dart
  lib/blocs/signup/signup_bloc.dart
  lib/blocs/wishlist/wishlist_bloc.dart
  lib/core/models/user_model.dart
  lib/resources/user/firebase_user.dart
  lib/screens/app.dart
  lib/screens/detail_offers/components/carousel_options.dart
  lib/screens/detail_offers/detail_offer.dart
  lib/screens/explore/explore.dart
  lib/screens/explore_list/explore_list.dart
  lib/screens/filter/components/filter_counter_container.dart
  lib/screens/filter/filter_page.dart
  lib/screens/home/home.dart
  lib/screens/hosting/components/host_appbar.dart
  lib/screens/hosting/components/host_select_menu_guest_num.dart
  lib/screens/hosting/components/host_select_menu_type_size.dart
  lib/screens/hosting/host_page_address.dart
  lib/screens/hosting/host_page_type_size.dart
  lib/screens/interest/components/interest_select_menu_gender.dart
  lib/screens/interest/interest_page_pet.dart
  lib/screens/personal_info/components/app_bar_personal_info.dart
  lib/screens/personal_info/components/gender_personal_info.dart
  lib/screens/personal_info/components/single_input_personal_info.dart
  lib/screens/personal_info/personal_info.dart
  lib/screens/profile/components/username_and_profile_button.dart
  lib/screens/profile/profile.dart
Labels: help wanted

#97 Feature/detail offer
  lib/blocs/explore_people/explore_people_bloc.dart
  lib/blocs/home/home_bloc.dart
  lib/blocs/offer_detail/offer_detail_bloc.dart
  lib/blocs/offer_detail/offer_detail_event.dart
  lib/blocs/offer_detail/offer_detail_state.dart
  lib/blocs/profile/profile_bloc.dart
  lib/core/definitions.dart
  lib/core/models/house_offer_model.dart
  lib/screens/app.dart
  lib/screens/core/navigation.dart
  lib/screens/detail_offers/components/bottom_navigation.dart
  lib/screens/detail_offers/components/card_image.dart
  lib/screens/detail_offers/components/circle_back_Button.dart
  lib/screens/detail_offers/components/circle_favorite_Button.dart
  lib/screens/detail_offers/components/circle_share_Button.dart
  lib/screens/detail_offers/components/custom_app_bar.dart
  lib/screens/detail_offers/components/description.dart
  lib/screens/detail_offers/components/description_offers.dart
  lib/screens/detail_offers/components/row_components.dart
  lib/screens/detail_offers/detail_offer.dart
  lib/screens/explore/components/persons_grid_view.dart
  lib/screens/explore_list/components/place_item.dart
  lib/screens/explore_list/explore_list.dart
  lib/screens/filter/components/filter_counter_container.dart
  lib/screens/filter/filter_page.dart
  lib/screens/help/components/article.dart
  lib/screens/home/home.dart
  lib/screens/hosting/components/host_select_menu_desc_hotel.dart
  lib/screens/hosting/host_page_amenities.dart
  lib/screens/hosting/host_page_guest_number.dart
  lib/screens/hosting/host_page_photos.dart
  lib/screens/hosting/host_page_review.dart
  lib/screens/personal_info/personal_info.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#96 Bottomsheet/alignment
  lib/screens/explore_list/explore_list.dart
  lib/screens/explore_people/components/place_item.dart
  lib/screens/filter/components/filter_appbar.dart
  lib/screens/filter/filter_page.dart
Labels: enhancement

#98 Serviços
  lib/screens/explore_list/components/explore_app_bar.dart
  lib/screens/explore_list/components/place_item.dart
  lib/screens/terms/components/default_text.dart
  lib/screens/terms/terms_page.dart
Labels: enhancement

#102 Rental bloc
  lib/blocs/home/home_bloc.dart
  lib/blocs/person_list/person_list_bloc.dart
  lib/blocs/person_list/person_list_event.dart
  lib/blocs/person_list/person_list_state.dart
  lib/blocs/rental_list/rental_list_bloc.dart
  lib/blocs/rental_list/rental_list_event.dart
  lib/blocs/rental_list/rental_list_state.dart
  lib/core/models/house_offer_model.dart
  lib/core/models/interest_offer_model.dart
  lib/screens/app.dart
  lib/screens/core/notFound.dart
  lib/screens/home/home.dart
  lib/screens/person_list/person_list.dart
  lib/screens/rental_list/components/rental_unit_card.dart
  lib/screens/rental_list/rental_list.dart
Labels: enhancement

#103 Feature/favorito
  lib/blocs/explore_list/explore_list_bloc.dart
  lib/screens/explore_list/components/place_item.dart
Labels: enhancement

#110 fix: merge do anterior removeu o que foi desenvolvido
  lib/blocs/home/home_bloc.dart
  pubspec.lock
  pubspec.yaml
Labels: bugfix
